name: Deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  GODOT_VERSION: 4.6.2

jobs:
  export-html5:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:$GODOT_VERSION
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Setup
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/$GODOT_VERSION.stable ~/.local/share/godot/export_templates/$GODOT_VERSION.stable
      
      - name: Export project to Web
        run: |
          mkdir export
          godot --verbose --headless --export-release "Web" ./export/index.html
      
      - name: Install rsync
        run: |
          apt-get update -qq && apt-get install -qqq rsync
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: export
          single-commit: true
